Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDoApp.urls')),
]

Project/ToDoApp/urls.py
from django.urls import path
from .views import *

app_name='ToDoApp'
urlpatterns = [
    path('', ToDoList.as_view(), name='home'),
    path('create/', CreateToDo.as_view(), name='create'),
    path('<slug>', ToDoDetails.as_view(), name='details'),
    path('update/<slug>', ToDoUpdate.as_view(), name='update'),
    path('delete/<slug>', DeleteToDo.as_view(), name='delete'),
]

Project/ToDoApp/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from django.template.defaultfilters import slugify
# Create your models here.
class ToDo(models.Model):
    title = models.CharField(max_length =200)
    slug= models.SlugField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    tools = models.CharField(max_length=200)
    daycount = models.PositiveIntegerField()
    endgoal = models.CharField(max_length=200)
    due = models.DateTimeField(auto_now_add=False, blank=True, default=datetime.now())

    
    def __str__(self):
        return self.title
    
    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         self.slug = slugify(self.title)
    #     return super().save(*args, **kwargs)
        
    def get_absolute_url(self):
        return reverse("ToDoApp:details", kwargs={"slug": self.slug})

Project/ToDoApp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import *
from django import forms
import datetime
from django.db.models import Q
# Create your views here.
class CreateToDo(CreateView):
    model = ToDo
    template_name = "ToDoApp/todo_form.html"
    fields = ['title', 'description', 'tools', 'daycount', 'endgoal', 'due']

class ToDoList(ListView):
    model = ToDo
    context_object_name = 'tasks'
    template_name= 'ToDoApp/home.html'
    
    extra_context = {'due' : datetime.datetime(2022, 10, 30)}
    
    def get_queryset(self):
        q = self.request.GET.get('q', '')
        multiple_search = Q(Q(title__icontains=q) | Q(tools__icontains=q))
        tasks = ToDo.objects.filter(multiple_search)
        
        return tasks
    

    
class ToDoDetails(DetailView):
    model = ToDo
    template_name='ToDoApp/details.html'
    context_object_name = 'task_detail'
    
class ToDoUpdate(UpdateView):
    model =ToDo
    fields = ['title', 'description', 'tools', 'daycount', 'endgoal', 'due']
    
class DeleteToDo(DeleteView):
    model = ToDo
    template_name = "ToDoApp/delete.html"
    success_url = reverse_lazy("ToDoApp:home")
    context_object_name = 'task'

Project/ToDoApp/templates/ToDoApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" 
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" 
        rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
        crossorigin="anonymous">
    <title>{% block title %}{% endblock %} | Walobwa</title>
</head>
<body>
    <nav class="nav w-screen h-14 flex justify-between items-center bg-purple-500 text-white">
        <div class="items">
            <a href = "{% url 'ToDoApp:home' %}" class="mx-4 hover:text-purple-800 font-bold">HOME</a>
            <a href = "#" class="mx-4 hover:text-purple-800 font-bold ">ABOUT</a>
        </div>
        <div class="create">
            <a href = "{% url 'ToDoApp:create' %}" class="mr-5 hover:text-purple-800  font-bold">
                Create task<span class="fa-solid fa-plus px-3"></span>
            </a>
        </div>

    </nav>

    
    {% block content %}
    
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"  
    integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" 
    crossorigin="anonymous"></script>
</body>
</html>

Project/ToDoApp/templates/ToDoApp/delete.html
{% extends 'ToDoApp/base.html' %}

{% block content %}

    <div class="container text-center absolute top-1/2 left-1/3 w-1/3 shadow-lg bg-gray-700 text-white rounded">
        <div class="p-3">
            <p>Are you sure you want to delete {{task.title}}</p>
            <form method= 'POST'>
                {% csrf_token %}
            <button class="btn btn-danger">Yes</button>
            <a href="{% url 'ToDoApp:details' slug=task.slug %}" class="btn btn-success">No</a>
            </form>
        </div>
    </div>
{% endblock %}

Project/ToDoApp/templates/ToDoApp/details.html
{% extends 'ToDoApp/base.html' %}

{% block title %}
    {{task_detail.title}}
{% endblock %}

{% block content %}
    <div class="container text-center translate-y-1/4 bg-gray-500 rounded  w-2/3 shadow-lg text-purple-300 ">
        <div class="details leading-loose p-3">
            <strong class="text-2xl text-white">Name of task:</strong> <br><p>{{task_detail.title}}</p>
            <strong class="text-2xl text-white">Date created:</strong> <br><p>{{task_detail.created_at}}</p>
            <strong class="text-2xl text-white">Task Due:</strong> <br><p>{{task_detail.due | timeuntil }}</p>
            <strong class="text-2xl text-white">About task:</strong> <br><p>{{task_detail.description}}</p>
            <strong class="text-2xl text-white">Tools required for task:</strong> <br><p>{{task_detail.tools}}</p>
            <strong class="text-2xl text-white">What to achieve from task:</strong><br> <p>{{task_detail.endgoal}}</p><br>
            <a href="{% url 'ToDoApp:update' slug=task_detail.slug %}" class="btn btn-warning">Update</a>
            <a href="{% url 'ToDoApp:delete' slug=task_detail.slug %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
    
{% endblock %}

Project/ToDoApp/templates/ToDoApp/home.html
{% extends 'ToDoApp/base.html' %}

{% block content %}
    <form class="">
        <input type="text" name="q" class="form-control absolute top-20 left-1/4 w-1/2" placeholder="search by task or tools">
    </form>
    <div class="container   p-3 bg-gray-700 rounded text-purple-300 shadow-lg translate-y-40">
        
            <div class="flex font-bold">
                <h5 class="ml-8">Tasks</h5>
                <h5 class="mx-auto">Date Created</h5>
                <h5 class="mr-20 pr-20">Due</h5>
            </div>
            {% for task in tasks %}

            <div class="tasks py-2">
                <div class="border-solid border-2 border-purple-300 p-3 rounded">
                    <a href="{{task.slug}}" class="title font-bold hover:text-white">
                        <span>{{ task.title}}</span>
                        <span class="fa-solid fa-door-open text-purple-300 font-bold"></span>
                    </a>
                    <span class="dates ml-80">{{ task.created_at }}</span>
                    <span class="duetime float-right mr-32"><span class="fa-solid fa-circle animate-ping pr-2"></span> {{task.due | timeuntil }}</span>
                </div>
            </div> 
        {% endfor %}
    </div>
{% endblock %}

Project/ToDoApp/templates/ToDoApp/todo_form.html
{% extends 'ToDoApp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container bg-gray-700 text-purple-300 text-center translate-y-1/4 rounded w-1/2 shadow-lg">

        <form method="POST" class="p-3"> 

            {% csrf_token %}

            {{form | crispy}}

            <button type="submit" class="btn btn-primary mt-3">Create Task</button>
        </form>
    </div>
{% endblock %}